# vim:sw=2:et:

dist: xenial
sudo: false
language: erlang
notifications:
  email:
    recipients:
      - alerts@rabbitmq.com
    on_success: never
    on_failure: always
addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      - awscli
      - dotnet-sdk-2.0.0
      - maven
cache:
  apt: true
env:
  global:
    - secure: hsWxOPcSAXQU9CKQSh829aPLt7oFim8lYVPMSfR0GH0JsnxWgayk2w3tyAblOJqpXTKPqYb+TfyeTOc+QQM8pcEtvi5jtr+GAqovI3UkXpR08J5ImVZVf3sfD4s92uoRjw0u8ift/qZxpDLpdDCKJibe3hRMxlvo5LQ5kCkNGFs=
    - secure: D2xypqCxIxyhX2/PtXhiWa8kZF9itwhvDK3mxEI+67AM8zJBtrIlIcHifnFMM1RDjFzuBWq5t0BAbyuAGUw0EcjOnc3xW01N/ZG4DaHgXjurDSY0rCfkYLHltFjxJTbx2bH6nmgjdKYRb4W9hQJVcB7vtd1g7kVlzYkNevz4Sfk=

otp_release:
  - "21.3"

before_script:
  - elixir --version
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, v3.8.x branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream v3.8.x:v3.8.x || :
    git fetch upstream master:master || :

script:
  - make xref
  - make tests

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
